/**
 * 🐟 AZERCLAW Share Command
 * Export a session as a shareable markdown file.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
const { getSessionStore } = require('../../memory/store');
const { fishBox, fishSuccess, fishError, fishInfo } = require('../animations/fish');

const SHARES_DIR = path.join(os.homedir(), '.azerclaw', 'shares');

export async function runShare(sessionId?: string): Promise<void> {
  const store = getSessionStore();
  
  if (!fs.existsSync(SHARES_DIR)) {
    fs.mkdirSync(SHARES_DIR, { recursive: true });
  }

  // 1. Resolve Session
  let session;
  if (!sessionId) {
    const recent = store.getRecent(1);
    if (recent.length === 0) {
      fishError('No sessions found to share.');
      return;
    }
    session = store.get(recent[0].id);
  } else {
    session = store.get(sessionId);
  }

  if (!session) {
    fishError(`Session "${sessionId}" not found.`);
    return;
  }

  // 2. Format to Markdown
  let markdown = `# 🐟 AZERCLAW Session Report\n\n`;
  markdown += `**Title:** ${session.title}\n`;
  markdown += `**Date:** ${new Date(session.createdAt).toLocaleString()}\n`;
  markdown += `**Session ID:** \`${session.id}\`\n\n`;
  markdown += `---\n\n`;

  for (const msg of session.messages) {
    const role = msg.role.toUpperCase();
    const emoji = role === 'USER' ? '👤' : (role === 'ASSISTANT' ? '🐟' : '🔧');
    
    markdown += `### ${emoji} ${role}\n\n`;
    
    if (msg.content) {
      markdown += `${msg.content}\n\n`;
    }
    
    if (msg.toolCalls) {
      markdown += `#### 🛠️ Tool Calls\n`;
      for (const call of msg.toolCalls) {
        markdown += `- \`${call.function.name}\` with args: \`${call.function.arguments}\`\n`;
      }
      markdown += `\n`;
    }
    
    markdown += `---\n\n`;
  }

  markdown += `*Generated by AZERCLAW 2.0 — Diabolical Edition*\n`;

  // 3. Save to file
  const fileName = `share_${session.id}_${Date.now()}.md`;
  const filePath = path.join(SHARES_DIR, fileName);
  
  fs.writeFileSync(filePath, markdown);
  
  fishBox('MISSION EXPORTED', [
    `  Session:  ${chalk.cyan(session.title)}`,
    `  File:     ${chalk.yellow(filePath)}`,
    '',
    chalk.dim('  You can now share this markdown file with your team.'),
    chalk.dim('  Hosted links coming in the next Vought update.')
  ]);
  
  // Open file on macOS
  if (process.platform === 'darwin') {
    const { exec } = require('child_process');
    exec(`open "${filePath}"`);
  }
}
